version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    versioning-strategy: increase
    reviewers:
      - strapi/maintainers
    open-pull-requests-limit: 5
